#!/bin/sh

set -e

# core.editorに設定したいもの
# merge,rebaseなどの時に起動する
CORE_EDITOR=vi

# commitじゃなかった場合(mergeとかrebaseとか)の場合はCORE_EDITORに渡す
if [[ ! "$1" = *COMMIT_EDITMSG ]]; then
    $CORE_EDITOR $1
    exit 0
fi

CURRENT_DIR=$(cd $(dirname $0); pwd)
MSGLIST_FILE=$CURRENT_DIR/.gscme_msglist

# .gscme_msglistファイルが無い場合は作る
# デフォルトの質問リストをセットする
if [[ ! -r $MSGLIST_FILE ]]; then
    /bin/echo "please edit .gscme_msglist file."
    cat <<EOF > $MSGLIST_FILE
どのような変更ですか？
この変更によって,どんなことが起きますか？
なぜその変更が必要でしたか？
参考URLなど（あれば）
EOF
fi

COMMIT_MSG=""

exec 3< $MSGLIST_FILE
while read line 0<&3
do
    if [[ ${line} == \#* ]]; then
        continue
    fi
    /bin/echo -n "$line > "
    read msg
    COMMIT_MSG="${COMMIT_MSG} ${msg}"
done
exec 3<&-

/bin/echo -n $COMMIT_MSG >> $1
exit 0
