#!/bin/sh

set -e

# core.editorに設定したいもの
# merge,rebaseなどの時に起動する
CORE_EDITOR=vi

# commitじゃなかった場合(mergeとかrebaseとか)の場合はCORE_EDITORに渡す
if [[ ! "$1" = *COMMIT_EDITMSG ]]; then
    $CORE_EDITOR $1
    exit 0
fi

CURRENT_DIR=$(cd $(dirname $0); pwd)
MSGLIST_FILE=$CURRENT_DIR/.gscme_msglist
SAMPLE_MSGLIST_FILE=$CURRENT_DIR/sample_msglist/.gscme_msglist_present_tense_subject

# .gscme_msglistファイルが無い場合は作る
# デフォルトの質問リストをセットする
if [[ ! -r $MSGLIST_FILE ]]; then
    /bin/echo "please edit .gscme_msglist file."
    cat $SAMPLE_MSGLIST_FILE > $MSGLIST_FILE
fi

COMMIT_MSG=""

exec 3< $MSGLIST_FILE
while read line 0<&3
do
    if [[ ${line} == \#* ]]; then
        continue
    fi
    if [[ ${line} ]]; then
        /bin/echo -n "$line > "
        read msg
        COMMIT_MSG="${COMMIT_MSG}${msg}"
    fi
    COMMIT_MSG="${COMMIT_MSG}\n"
done
exec 3<&-

echo $COMMIT_MSG >> $1
exit 0
