#!/bin/sh

set -e

# core.editorに設定したいもの
CORE_EDITOR=vi

# commitじゃなかった場合(mergeとかrebaseとか)の場合はcore.editorに渡す
if [[ ! "$1" = *COMMIT_EDITMSG ]]; then
    $CORE_EDITOR $1
    exit 0
fi

# .gscme_msglistファイルが無い場合は作る
if [[ ! -r .gscme_msglist ]]; then
    /bin/echo "please edit .gscme_msglist file."
    cat <<EOF > .gscme_msglist
どのような変更ですか？
この変更によって,どんなことが起きますか？
なぜその変更が必要でしたか？
参考URLなど（あれば）
EOF
fi

COMMIT_MSG=""

exec 3< .gscme_msglist
while read line 0<&3
do
    /bin/echo -n "$line > "
    read msg
    COMMIT_MSG="${COMMIT_MSG} ${msg}"
done
exec 3<&-

/bin/echo -n $COMMIT_MSG >> $1
exit 0
